In [1]:
PATH_TRAIN = '../data/dev.txt'

In [9]:
with open('./data.txt', 'w', encoding='utf-8') as f:
    for item in data_train:
        f.write('%s\n'% item)

In [2]:
def read_line_by_line(path_file):
    data = []
    with open(path_file, 'r', encoding='utf-8') as f:
        for line in f.readlines():
            data.append(line.strip())
    return data

In [3]:
data_train = read_line_by_line(PATH_TRAIN)

In [4]:
len(data_train)

3228507

In [6]:
data_train = data_train[:100000]

In [9]:
words = []
cap = []
pun = []
with open(PATH_TRAIN, 'r', encoding='utf-8') as f:
    for line in f.readlines():
        # print(line)
        # line = line.lstrip().rstrip()
        # print(line)
        # break
        line = line.split('\t')
        words.append(line[0])
        cap.append(line[1])
        pun.append(line[2])


In [10]:
import numpy as np

In [11]:
words = np.unique(words).tolist()

In [12]:
len(words)

76557

In [13]:
cap = np.unique(cap).tolist()

In [14]:
len(cap)

3

In [15]:
cap

['0', '1', '2']

In [16]:
pun = np.unique(pun).tolist()

In [17]:
pun

['COMMA\n', 'O\n', 'PERIOD\n', 'QMARK\n']

In [19]:

def readfile(filename,eos_marks=['PERIOD', 'QMARK']):
    paragraphs = []
    cap_labels = []
    punc_labels = []
    max_len_seq = 50
    with open(filename, mode="r", encoding="utf-8") as f:
        paragraph, cap_label , punc_label = [], [], []
        for line in f:
            line = line.lstrip().rstrip()
            word, cap, punc = line.split('\t')

            if len(paragraph) < max_len_seq:
                paragraph.append(word)
                cap_label.append(int(cap))
                punc_label.append(punc)
            if len(paragraph) == max_len_seq:

                i = len(paragraph) - 1
                while i > 0:

                    if punc_label[i] in eos_marks:
                        if i == (max_len_seq - 1):
                            paragraphs.append(paragraph)
                            cap_labels.append(cap_label)
                            punc_labels.append(punc_label)
                            paragraph, cap_label , punc_label = [], [], []
                        else:
                            paragraphs.append(paragraph[:i+1])
                            cap_labels.append(cap_label[:i+1])
                            punc_labels.append(punc_label[:i+1])
                            paragraph = paragraph[i + 1:]
                            cap_label = cap_label[i + 1:]
                            punc_label = punc_label[i + 1:]
                        break
                    else:
                        i = i - 1

                if len(paragraph) == max_len_seq:
                    paragraph, cap_label , punc_label = [], [], []
        
    return list(zip(paragraphs, cap_labels, punc_labels))

In [20]:
lines = readfile(PATH_TRAIN)

In [35]:
lines[13]

(['những',
  'lao',
  'động',
  'sáng',
  'tạo',
  'của',
  'họ',
  'phải',
  'được',
  'ghi',
  'nhận',
  'và',
  'nghệ',
  'sĩ',
  'sẽ',
  'cảm',
  'nhận',
  'được',
  'những',
  'nỗ',
  'lực',
  'cố',
  'gắng',
  'xuất',
  'phát',
  'từ',
  'tâm',
  'huyết',
  'đó',
  'không',
  'bị',
  'uổng',
  'phí'],
 [1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 ['O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'COMMA',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'PERIOD'])

In [6]:
from dataloader import readfile

/Users/vinbrain/opt/anaconda3/envs/myenv/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [7]:
data = readfile('./data.txt')

In [8]:
len(data[1][2])

29

In [9]:
class InputExample(object):
    """A single training/test example for simple sequence classification."""

    def __init__(self, guid, text=None, cap_label=None, punc_label=None):
        """Constructs a InputExample.
        Args:
            guid: Unique id for the example.
            text_a: string. The untokenized text of the first sequence. For single
            sequence tasks, only this sequence must be specified.
            text_b: (Optional) string. The untokenized text of the second sequence.
            Only must be specified for sequence pair tasks.
            label: (Optional) string. The label of the example. This should be
            specified for train and dev examples, but not for test examples.
        """
        self.guid = guid
        self.text = text
        self.cap_label = cap_label
        self.punc_label = punc_label

In [10]:
examples = []
for i, (sentence,cap_label,punc_label) in enumerate(data):
    guid = "%s-%s" % ('test', i)
    text = ' '.join(sentence)
    cap_label = cap_label
    punc_label = punc_label
    examples.append(InputExample(guid=guid, text=text, cap_label=cap_label,punc_label=punc_label))

In [11]:
examples[0].text

'trong khi người ta đang kháo nhau về việc một ông trùm trung đông sắp rót tiền vào để cứu leeds united thoát khỏi cơn khủng hoảng thì đội bóng áo trắng đã tìm được chiến thắng đầu tiên của mình sau chuỗi 5 trận thất bại liên tiếp'

In [12]:
from transformers import AutoTokenizer

In [13]:
tokenizer = AutoTokenizer.from_pretrained("vinai/phobert-base")

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


In [14]:
tokenizer

PreTrainedTokenizer(name_or_path='vinai/phobert-base', vocab_size=64000, model_max_len=256, is_fast=False, padding_side='right', special_tokens={'bos_token': '<s>', 'eos_token': '</s>', 'unk_token': '<unk>', 'sep_token': '</s>', 'pad_token': '<pad>', 'cls_token': '<s>', 'mask_token': '<mask>'})

In [15]:
punc_label_set = [ 'O', 'PERIOD', 'COMMA', 'QMARK','[CLS]', '[SEP]']
punc_label_map = {label: i for i, label in enumerate(punc_label_set)}

In [16]:
punc_label_map

{'O': 0, 'PERIOD': 1, 'COMMA': 2, 'QMARK': 3, '[CLS]': 4, '[SEP]': 5}

In [17]:
len(data)

2367

In [18]:
class InputFeatures(object):
    """A single set of features of data."""

    def __init__(self, 
                    input_ids, 
                    attention_mask, 
                    words_lengths, 
                    attention_mask_label, 
                    cap_label, 
                    punc_label
                    ):
        self.input_ids = input_ids
        self.attention_mask = attention_mask
        self.words_lengths = words_lengths
        self.attention_mask_label = attention_mask_label
        self.cap_label = cap_label
        self.punc_label = punc_label

In [19]:
features = []
for example in examples:
    textlist = example.text.split(' ')
    cap_label_list = example.cap_label
    punc_label_list = example.punc_label

    if len(textlist) > 120:
        textlist = textlist[:120-2]
        cap_label_list = cap_label_list[:120-2]
        punc_label_list = punc_label_list[:120-2]


    tokens = []
    cap_labels = []
    punc_labels = []
    words_lengths = []
    attention_mask_label = []
    attention_mask = []
    for i, word in enumerate(textlist):
        token = tokenizer.tokenize(word)
        if not token:
            token = [tokenizer.unk_token]
        tokens.extend(token)
        words_lengths.append(len(token))
        cap_label = cap_label_list[i]
        punc_label = punc_label_list[i]
        cap_labels.append(cap_label)
        punc_labels.append(punc_label_map[punc_label])
        attention_mask_label.append(1)

    tokens += [tokenizer.sep_token]
    cap_labels += [0]
    punc_labels += [punc_label_map['[SEP]']]
    words_lengths += [1]
    attention_mask_label += [1]

    tokens = [tokenizer.cls_token] + tokens
    cap_labels = [0] + cap_labels
    punc_labels = [punc_label_map['[CLS]']] + punc_labels
    words_lengths = [1] + words_lengths
    attention_mask_label = [1] + attention_mask_label


    input_ids = tokenizer.convert_tokens_to_ids(tokens)
    attention_mask = [1] * len(input_ids)


    padding_length = 120 - len(cap_labels)
    if padding_length > 0:
        cap_labels = cap_labels + ([0] * padding_length)
        words_lengths = words_lengths + ([1]*padding_length)
        punc_labels = punc_labels + ([punc_label_map["O"]]*padding_length)
        attention_mask_label = attention_mask_label + ([0]*padding_length)
    
    features.append(InputFeatures(input_ids=input_ids,
                                      attention_mask=attention_mask,
                                      words_lengths=words_lengths,
                                      attention_mask_label=attention_mask_label,
                                      cap_label=cap_labels,
                                      punc_label=punc_labels))


In [20]:
len(features)

2367

In [21]:
features[1].input_ids

[0,
 509,
 616,
 7,
 630,
 2183,
 1120,
 126,
 2545,
 29870,
 13922,
 6398,
 33,
 1865,
 286,
 69,
 14203,
 1494,
 4258,
 35,
 323,
 948,
 164,
 89,
 10,
 4623,
 96,
 8,
 882,
 48,
 354,
 3959,
 15,
 2723,
 55234,
 2]

In [22]:
all_input_ids = [f.input_ids for f in features]

In [23]:
import torch

In [24]:
def pad_concat(sample, pad_value=0):
    final_tensor = []
    max_length = max([torch.tensor(i).size(0) for i in sample]) # max len in data
    for i in sample:
        i = torch.tensor(i,dtype=torch.long)
        pa = max_length - i.size(0)
        if pa > 0:
            tensor = torch.nn.functional.pad(i, (0,pa), "constant", pad_value)
            final_tensor.append(tensor)
        else:
            final_tensor.append(i)
    return torch.stack(final_tensor)

In [25]:
all_input_ids = pad_concat(all_input_ids,tokenizer.pad_token_id)

In [26]:
all_input_ids[0]

tensor([    0,    12,    26,    18,   237,    52, 35942,   138,    28,    49,
           16,    46,  3588,  2765,   553,   984,  7814,   123,    33,    24,
         1098,  2723, 55234,  4335, 49067,  1159,   353,  1145,  2544, 17439,
           54,   226,   301,   797,   769,    14,   240,    11,  2856,   616,
          127,  6937,     7,    68,    53,  1973,   173,   196, 10893,  6416,
         2657,   917,     2,     1,     1,     1,     1,     1,     1,     1,
            1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
            1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
            1,     1,     1,     1,     1,     1,     1,     1])

In [27]:
all_attention_mask = [f.attention_mask for f in features]
all_attention_mask = pad_concat(all_attention_mask,0)

In [28]:
all_attention_mask.shape

torch.Size([2367, 88])

In [29]:
all_words_lengths = torch.tensor([f.words_lengths for f in features], dtype=torch.long)

In [30]:
all_words_lengths.shape

torch.Size([2367, 120])

In [31]:
all_attention_mask_label = torch.tensor([f.attention_mask_label for f in features], dtype=torch.long)
all_cap_label = torch.tensor([f.cap_label for f in features], dtype=torch.long)
all_punc_label = torch.tensor([f.punc_label for f in features], dtype=torch.long)


In [32]:
from transformers.models.roberta.modeling_roberta import RobertaPreTrainedModel, RobertaModel
from torch.utils.data import TensorDataset, SequentialSampler, DataLoader

In [33]:
dataset = TensorDataset(
        all_input_ids, all_words_lengths, all_attention_mask, all_attention_mask_label, all_cap_label, all_punc_label
    )

In [34]:
sampler = SequentialSampler(dataset)

In [35]:
dataloader = DataLoader(dataset, sampler=sampler, batch_size=4)

In [36]:
roberta = RobertaModel.from_pretrained("vinai/phobert-base")

Some weights of the model checkpoint at vinai/phobert-base were not used when initializing RobertaModel: ['lm_head.layer_norm.bias', 'lm_head.decoder.bias', 'lm_head.bias', 'lm_head.decoder.weight', 'lm_head.layer_norm.weight', 'lm_head.dense.weight', 'lm_head.dense.bias']
- This IS expected if you are initializing RobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [57]:
batch[-2].view(-1)

tensor([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [37]:
for i, batch in enumerate(dataloader):
    outputs = roberta(batch[0], attention_mask=batch[2])
    break

In [38]:
context_embedding = outputs[0]

In [39]:
context_embedding.shape

torch.Size([4, 88, 768])

In [40]:
batch_size = batch[0].shape[0] # batch_size
max_sub_word = batch[0].shape[1] # max_sub_word + padding
max_word = batch[1].shape[1]

In [41]:
batch_size

4

In [42]:
max_sub_word

88

In [43]:
max_word

120

In [48]:
a = torch.zeros((1, 4,3))

In [49]:
a

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [50]:
a[0][2][0:2] = 1

In [51]:
a

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [1., 1., 0.],
         [0., 0., 0.]]])

In [81]:
align_matrix = torch.zeros((batch_size, max_word, max_sub_word))

In [82]:
align_matrix.shape

torch.Size([4, 120, 88])

In [86]:
for i, sample_length in enumerate(batch[1]):
    for j in range(len(sample_length)):
        start_idx = torch.sum(sample_length[:j])
        align_matrix[i][j][start_idx: start_idx + sample_length[j]] = 1 if sample_length[j] > 0 else 0

In [90]:
align_matrix.shape

torch.Size([4, 120, 88])

In [91]:
context_embedding.shape

torch.Size([4, 88, 768])

In [93]:
torch.bmm(align_matrix, context_embedding).shape

torch.Size([4, 120, 768])

In [47]:
torch.sum(batch[1][0][:0])

tensor(0)

In [121]:
align_matrix

tensor([[[1., 0., 0.,  ..., 0., 0., 0.],
         [0., 1., 0.,  ..., 0., 0., 0.],
         [0., 0., 1.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[1., 0., 0.,  ..., 0., 0., 0.],
         [0., 1., 0.,  ..., 0., 0., 0.],
         [0., 0., 1.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[1., 0., 0.,  ..., 0., 0., 0.],
         [0., 1., 0.,  ..., 0., 0., 0.],
         [0., 0., 1.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[1., 0., 0.,  ..., 0., 0., 0.],
         [0., 1., 0.,  ..., 0., 0., 0.],
         [0., 0., 1.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 

In [58]:
def f1(a,b):
    return 2*a*b/(a+b)

In [59]:
f1(0.9298,0.9192)

0.9244696160086534